### ISSUE TITLE
请问每个网络分别对应哪个代码仓呢

### ISSUE THREAD

**Issue by xiexu666** [IronSublimate/NCNN_ObjectDetection#2]

**Comment by IronSublimate** [comment]
网络的模型都放在app/src/main/assets 里了，可以在程序的settings 里切换😊

**Comment by xiexu666** [comment]
> 网络的模型都放在app/src/main/assets 里了，可以在程序的settings 里切换😊

我还想更改yolov5，yolox为其它版本他们对应的训练代码仓是哪个呢

**Comment by IronSublimate** [comment]
训练请去yolov5的源代码仓库，这个只是用训练好的结果在Android进行推理的
